# This is a basic workflow to help you get started with Actions

name: CI Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Runs commands using the runners shell
      - name: Install modules
        run: npm install

      - name: Run ESlint Check
        run: npm run lint

      - name: Run Prettier Check
        run: npm run prettier

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run rollup

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
